AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.8

  SAM Template for LambdaDeckProducer

Globals:
  Function:
    Timeout: 60
    Environment:
      Variables:
        DECKS_CONSUMER_QUEUE: decks-queue
        
Resources:
  LambdaDeckProducer:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
    Metadata:
      Dockerfile: ./lambdas/deck_producer/Dockerfile
      DockerContext: ../../
      DockerTag: python3.8-v1