AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.8

  SAM Template for LambdaDeckConsumer

Globals:
  Function:
    Timeout: 45
    Environment:
      Variables:
        DECKS_DOWNLOADED_QUEUE: decks-downloaded-queue
        
Resources:
  LambdaDeckConsumer:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Policies:
        - AmazonSQSFullAccess        
    Metadata:
      Dockerfile: ./lambdas/deck_consumer/Dockerfile
      DockerContext: ../../
      DockerTag: python3.8-v1